//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Hei10.Domain.Infrastructure;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;

namespace Hei10.Domain.Models
{
    public partial class SysApartment : AggregateRoot
    {
        public virtual long Pid
        {
            get;
            set;
        }

        public virtual int Sort
        {
            get;
            set;
        }

        [MaxLength(50),Required]
        public virtual string Name
        {
            get;
            set;
        }

        [MaxLength(250)]
        public virtual string Remark
        {
            get;
            set;
        }

        [MaxLength(100)]
        public string TreePath { get; set; }

    }
}

