//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Hei10.Domain.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Hei10.Domain.Models
{
    public class UserRole2Apartment : AggregateRoot
    {
        public virtual long RoleId
        {
            get;
            set;
        }

        public virtual long ApartmentId
        {
            get;
            set;
        }

    }

}